services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messages
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 15s
      timeout: 5s
      retries: 10

  app-js:
    build: ./app-js
    networks:
      - load-balancer
      - database
    depends_on:
      mysql:
        condition: service_healthy

  app-python:
    build: ./app-python
    networks:
      - load-balancer
      - database
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-js
      - app-python
    networks:
      - load-balancer

networks:
  load-balancer:
    driver: bridge
  database:
    driver: bridge
